/* ephones constant */

export const PHONE_LIST_REQUEST = 'PHONE_LIST_REQUEST'
export const PHONE_LIST_SUCCESS = 'PHONE_LIST_SUCCESS'
export const PHONE_LIST_FAIL = 'PHONE_LIST_FAIL'

export const SINGLE_PHONE_REQUEST = 'SINGLE_PHONE_REQUEST'
export const SINGLE_PHONE_SUCCESS = 'SINGLE_PHONE_SUCCESS'
export const SINGLE_PHONE_FAIL = 'SINGLE_PHONE_FAIL'

export const PHONE_DELETE_REQUEST = 'PHONE_DELETE_REQUEST'
export const PHONE_DELETE_SUCCESS = 'PHONE_DELETE_SUCCESS'
export const PHONE_DELETE_FAIL = 'PHONE_DELETE_FAIL'

export const PHONE_CREATE_REQUEST = 'PHONE_CREATE_REQUEST'
export const PHONE_CREATE_SUCCESS = 'PHONE_CREATE_SUCCESS'
export const PHONE_CREATE_FAIL = 'PHONE_CREATE_FAIL'
export const PHONE_CREATE_RESET = 'PHONE_CREATE_RESET'

export const PHONE_UPDATE_REQUEST = 'PHONE_UPDATE_REQUEST'
export const PHONE_UPDATE_SUCCESS = 'PHONE_UPDATE_SUCCESS'
export const PHONE_UPDATE_FAIL = 'PHONE_UPDATE_FAIL'
export const PHONE_UPDATE_RESET = 'PHONE_UPDATE_RESET'

export const PHONE_CREATE_REVIEW_REQUEST = 'PHONE_CREATE_REVIEW_REQUEST'
export const PHONE_CREATE_REVIEW_SUCCESS = 'PHONE_CREATE_REVIEW_SUCCESS'
export const PHONE_CREATE_REVIEW_FAIL = 'PHONE_CREATE_REVIEW_FAIL'
export const PHONE_CREATE_REVIEW_RESET = 'PHONE_CREATE_REVIEW_RESET'

export const PHONE_TOP_REQUEST = 'PHONE_TOP_REQUEST'
export const PHONE_TOP_SUCCESS = 'PHONE_TOP_SUCCESS'
export const PHONE_TOP_FAIL = 'PHONE_TOP_FAIL'

/* cart and shipping constant */

export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

export const CART_ITEM_DECREASE = 'CART_ITEM_DECREASE'
export const CART_ITEM_INCREASE = 'CART_ITEM_INCREASE'
export const GET_TOTAL = 'GET_TOTAL'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

/* user constant */

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'


/* Order constant */

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

